import { declesAfter, picturesAfter } from "./asm-reader.js";

/** A TypeScript module generated from the cartridge listing, destined for engine/src/rom/. */
export interface GeneratedModule {
  readonly fileName: string;
  readonly source: string;
}

interface ConstantSpec {
  readonly name: string;
  readonly doc: string;
  readonly values: readonly (string | number)[];
}

interface TableSource {
  readonly name: string;
  readonly doc: string;
  readonly label: string;
}

const HEADER = "// Generated by `npm run rom` from docs/reference/utopia.asm. Do not edit.\n";
const ITEM_KINDS = 9;

const ISLAND_TABLES: readonly TableSource[] = [
  { name: "LEFT_ISLAND_OFFSETS", label: "LFT_ISLE_OFS_TBL", doc: "BACKTAB offsets, left island." },
  {
    name: "RIGHT_ISLAND_OFFSETS",
    label: "RGT_ISLE_OFS_TBL",
    doc: "BACKTAB offsets, right island.",
  },
  { name: "LEFT_ISLAND_CARDS", label: "LFT_ISLE_PIC_TBL", doc: "Land card per left offset." },
  { name: "RIGHT_ISLAND_CARDS", label: "RGT_ISLE_PIC_TBL", doc: "Land card per right offset." },
];

const ITEM_TABLES: readonly TableSource[] = [
  { name: "ITEM_PRICES", label: "PRICES", doc: "Gold price of items 1-9, in keypad order." },
  { name: "ITEM_COLOURS", label: "COLORS", doc: "Palette colour of items 1-9 (0 for boats)." },
];

/** Intellivision palette indices behind the listing's colour symbols. */
const COLOUR_SYMBOLS: Readonly<Record<string, number>> = {
  C_BLK: 0,
  C_BLU: 1,
  C_RED: 2,
  C_TAN: 3,
  C_DGR: 4,
  C_GRN: 5,
  C_YEL: 6,
  C_WHT: 7,
};

export function romModules(listing: string): GeneratedModule[] {
  const numbersUnder = (table: TableSource) => declesAfter(listing, table.label).map(wordValue);
  return [
    moduleOf("mob-pictures.ts", [mobPictures(listing)]),
    moduleOf("card-pictures.ts", [cardPictures(listing)]),
    moduleOf(
      "island-tables.ts",
      ISLAND_TABLES.map((table) => ({ ...table, values: numbersUnder(table) })),
    ),
    moduleOf(
      "item-tables.ts",
      ITEM_TABLES.map((table) => ({ ...table, values: numbersUnder(table).slice(0, ITEM_KINDS) })),
    ),
  ];
}

function mobPictures(listing: string): ConstantSpec {
  return {
    name: "MOB_PICTURES",
    doc: "Sprite (MOB) pictures #00-#25, 8 rows each; a 16-row sprite spans two pictures.",
    values: picturesAfter(listing, ".GFX_ANIM_5D1A"),
  };
}

function cardPictures(listing: string): ConstantSpec {
  return {
    name: "CARD_PICTURES",
    doc: "Background (GRAM) cards #00-#20: land, items, sinking boats and coastlines.",
    values: picturesAfter(listing, ".GFX_LIST_5E4A"),
  };
}

function wordValue(word: string): number {
  if (word.startsWith("$")) return parseInt(word.slice(1), 16);
  if (word in COLOUR_SYMBOLS) return COLOUR_SYMBOLS[word];
  const value = Number(word);
  if (Number.isNaN(value)) throw new Error(`Cannot read the listing word ${word}`);
  return value;
}

function moduleOf(fileName: string, constants: readonly ConstantSpec[]): GeneratedModule {
  return { fileName, source: HEADER + constants.map(constantSource).join("") };
}

function constantSource(constant: ConstantSpec): string {
  const type = typeof constant.values[0] === "string" ? "string" : "number";
  const values = constant.values.map((value) => JSON.stringify(value)).join(", ");
  return `\n/** ${constant.doc} */\nexport const ${constant.name}: readonly ${type}[] = [${values}];\n`;
}
