// Generated by `npm run rom` from docs/reference/utopia.asm. Do not edit.

/** BACKTAB offsets, left island. */
export const LEFT_ISLAND_OFFSETS: readonly number[] = [
  42, 61, 62, 63, 81, 82, 83, 101, 102, 103, 104, 105, 123, 124, 125, 126, 144, 145, 146, 147, 148,
  163, 164, 165, 167, 168, 169, 170, 171,
];

/** BACKTAB offsets, right island. */
export const RIGHT_ISLAND_OFFSETS: readonly number[] = [
  50, 51, 53, 56, 70, 71, 72, 73, 74, 75, 76, 90, 91, 94, 95, 96, 97, 115, 116, 117, 118, 136, 137,
  138, 155, 156, 157, 158, 177,
];

/** Land card per left offset. */
export const LEFT_ISLAND_CARDS: readonly number[] = [
  19, 20, 0, 21, 23, 0, 24, 29, 30, 0, 32, 21, 29, 0, 0, 21, 23, 0, 30, 32, 21, 25, 30, 31, 29, 30,
  28, 27, 26,
];

/** Land card per right offset. */
export const RIGHT_ISLAND_CARDS: readonly number[] = [
  20, 21, 19, 19, 23, 0, 27, 30, 28, 32, 24, 29, 31, 29, 0, 0, 21, 29, 0, 0, 21, 23, 0, 24, 25, 30,
  0, 31, 22,
];
