// Generated by `npm run rom` from docs/reference/utopia.asm. Do not edit.

/** Gold price of items 1-9, in keypad order. */
export const ITEM_PRICES: readonly number[] = [50, 40, 3, 35, 75, 60, 30, 40, 25];

/** Palette colour of items 1-9 (0 for boats). */
export const ITEM_COLOURS: readonly number[] = [0, 0, 4, 7, 2, 6, 0, 0, 0];
